# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.example.brandr.soa
canonical: http://example.org/br-and-r/soa
name: ScheduleOfActivityIG
status: draft
version: 0.1.1  
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  CDISC Operational Model (ODM): cdisc-odm.html
  Clinical Research Profile Backlog: deltas.html
  Developer Setup: developer.html
pages:
  index.md:
    title: Home
  cdisc-odm.md:
    title: CDISC Operational Model (ODM)
  developer.md:
    title: Developer Setup
  h2q-mc-lzzt.md:
    title: Study Design for H2Q-MC-LZZT
  deltas.md:
    title: Clinical Research Profile Backlog
