Instance: H2Q-MC-LZZT-Study-Visit-1
InstanceOf: SOAPlanDefinition
Usage: #example
Title: "Visit-1"
Description: "Planned Visit [Visit-1]"
* identifier[+].value = "VISIT-1"
* identifier[=].type = #PLAC
* identifier[=].use = #usual
* identifier[+].value = "SE.SCREENING_VISIT"
* identifier[=].system = "http://www.cdisc.org/ns/odm/v1.3/StudyDef#"
* identifier[=].type.coding[0].system = "http://www.cdisc.org/ns/odm/v1.3#"
* identifier[=].type.coding[0].display = "OID"
* identifier[=].type.text = "OID"
* identifier[=].use = #secondary
* extension[plannedStudyDay].valueInteger = -14
* status = #active
* action[+].title = "Record Visit Date"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Visit-Date"
* action[+].title = "Informed Consent "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Informed-Consent"
* action[+].title = "Patient number assigned "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Patient-number-assigned"
* action[+].title = "Hachinski 4 "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Hachinski-4"
* action[+].title = "MMSE 10-23 "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-MMSE-10-23"
* action[+].title = "Physical examination "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Physical-examination"
* action[+].title = "Medical History "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Medical-History"
* action[+].title = "Habits - Alcohol"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Habits-Alcohol"
* action[+].title = "Habits - Caffeine"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Habits-Caffeine"
* action[+].title = "Habits - Smoking"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Habits-Smoking"
* action[+].title = "Chest x-ray "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Chest-x-ray"
* action[+].title = "Vital signs/Temperature "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Vital-signs/Temperature"
* action[+].title = "ECG "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-ECG"
* action[+].title = "Placebo TTS test "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Placebo-TTS-test"
* action[+].title = "CT Scan"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-CT-Scan"
* action[+].title = "Concomitant Medications "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Concomitant-Medications"
* action[+].title = "Laboratory (Hema)"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Laboratory-Hema"
* action[+].title = "Laboratory (Chem)"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Laboratory-Chem-Visit1"
* action[+].title = "Laboratory (HBA1C)"
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Laboratory-Chem-HBA1C"
* action[+].title = "Laboratory (Urinalysis) "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Laboratory-Urinalysis"
* action[+].title = "ADAS-Cog "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-ADAS-Cog"
* action[+].title = "CIBIC+ "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-CIBIC+"
* action[+].title = "DAD "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-DAD"
* action[+].title = "NPI-X "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-NPI-X"
* action[+].title = "Adverse events "
* action[=].definitionUri = "ActivityDefinition/H2Q-MC-LZZT-Adverse-events"
