Instance: H2Q-MC-LZZT-Bundle-3
InstanceOf: Bundle
Usage: #example
Title: "H2Q-MC-LZZT Bundle 3"
Description: "Third Deliverable for the PHUSE Project — all H2Q-MC-LZZT constructed resources"
* type = #transaction
// ── Actors ───────────────────────────────────────────────────────────────────
* entry[+].resource = EliLillyAndCompany
* entry[=].fullUrl = "Organization/EliLillyAndCompany"
* entry[=].request.method = #POST
* entry[=].request.url = "Organization"
* entry[+].resource = SamGetWell
* entry[=].fullUrl = "Practitioner/SamGetWell"
* entry[=].request.method = #POST
* entry[=].request.url = "Practitioner"
// ── Study ─────────────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ResearchStudy
* entry[=].fullUrl = "ResearchStudy/H2Q-MC-LZZT-ResearchStudy"
* entry[=].request.method = #POST
* entry[=].request.url = "ResearchStudy"
// ── Eligibility ──────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ResearchStudy-Inclusion
* entry[=].request.method = #POST
* entry[=].request.url = "Group"
* entry[+].resource = H2Q-MC-LZZT-ResearchStudy-Exclusion
* entry[=].request.method = #POST
* entry[=].request.url = "Group"
// ── Activities ───────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ADAS-Cog
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Adverse-events
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Ambulatory-ECG-placed
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Ambulatory-ECG-removed
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Apo-E-genotyping
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-CIBIC
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-CT-Scan
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Chest-x-ray
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Concomitant-Medications
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-DAD
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-ECG
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Habits-Alcohol
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Habits-Caffeine
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Habits-Smoking
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hachinski-4
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hemoglobin-A1C
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Informed-Consent
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Laboratory-Chem
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Laboratory-Hemat
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Laboratory-Urinalysis
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-MMSE-10-23
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Medical-History
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Medications-dispensed
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Medications-returned
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-NPI-X
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Patient-number-assigned
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Patient-randomized
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Physical-examination
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Placebo-TTS-test
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Plasma-Specimen
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-drug-record
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Visit-Date
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vitalsigns-Temperature
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-DIABP-STANDING
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-DIABP-SUPINE
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-HEIGHT
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-PULSE-STANDING
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-PULSE-SUPINE
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-SYSBP-STANDING
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-SYSBP-SUPINE
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-WEIGHT
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
// ── Questionnaire ─────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-Questionnaire-TTS-Acceptability-Survey
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
// ── Observations ─────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ADAS-Cog-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Adverse-events-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Ambulatory-ECG-placed-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Ambulatory-ECG-removed-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Apo-E-genotyping-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-CIBIC-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-CT-Scan-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Chest-x-ray-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Concomitant-Medications-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-DAD-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-ECG-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Habits-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hachinski-4-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hematology-Panel-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hematology-HGB-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hematology-PLT-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hematology-WBC-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Hemoglobin-A1C-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Informed-Consent-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Laboratory-Chem-Hemat-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Laboratory-Urinalysis-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-MMSE-10-23-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Medical-History-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Medications-dispensed-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Medications-returned-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-NPI-X-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Patient-number-assigned-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Patient-randomized-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Physical-examination-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Placebo-TTS-test-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Plasma-Specimen-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-drug-record-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-TTS-Acceptability-Survey-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-TTS-Acceptability-Score-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-DIABP-STANDING-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-DIABP-SUPINE-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-HEIGHT-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-PULSE-STANDING-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-PULSE-SUPINE-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-SYSBP-STANDING-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-SYSBP-SUPINE-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-WEIGHT-Obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-signs-Temperature-Observations
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
// ── Vital sign sub-plans ──────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-HeartRate-BloodPressure
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-Vital-Signs-HeartRate-BloodPressure"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-Height-PD
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-Vital-Signs-Height-PD"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-Temperature-PD
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-Vital-Signs-Temperature-PD"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Vital-Signs-Weight-PD
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-Vital-Signs-Weight-PD"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
// ── Visit plans ───────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-1
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-2
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-3
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-4
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-5
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-6
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-7
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-8
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-9
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-10
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-11
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-12
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-Visit-13
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-ET-14
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-Study-RT-15
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
// ── Protocol design ───────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ProtocolDesign
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-ProtocolDesign"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
