Instance: H2Q-MC-LZZT-Bundle-4
InstanceOf: Bundle
Usage: #example
Title: "H2Q-MC-LZZT Bundle 4 — USDM-derived resources"
Description: "Fourth Deliverable — all resources generated from the USDM source (CDISC_Pilot_Study_v4_FIXED.json). Includes the ResearchStudy, visit PlanDefinitions with soaTimepoint timing and soaTransition graph edges, all ActivityDefinitions, ObservationDefinitions, Questionnaires, and eligibility Groups."
* type = #transaction

// ── Actors ────────────────────────────────────────────────────────────────────
* entry[+].resource = LILLY-USDM
* entry[=].fullUrl = "Organization/LILLY-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "Organization"
* entry[+].resource = Pers-001
* entry[=].fullUrl = "Practitioner/Pers-001"
* entry[=].request.method = #POST
* entry[=].request.url = "Practitioner"

// ── Study ─────────────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ResearchStudy-USDM
* entry[=].fullUrl = "ResearchStudy/H2Q-MC-LZZT-ResearchStudy-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "ResearchStudy"

// ── Eligibility ───────────────────────────────────────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ResearchStudy-Inclusion-USDM
* entry[=].fullUrl = "Group/H2Q-MC-LZZT-ResearchStudy-Inclusion-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "Group"
* entry[+].resource = H2Q-MC-LZZT-ResearchStudy-Exclusion-USDM
* entry[=].fullUrl = "Group/H2Q-MC-LZZT-ResearchStudy-Exclusion-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "Group"

// ── Activities ────────────────────────────────────────────────────────────────
* entry[+].resource = usdm-act-adverse-events
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-ambulatory-ecg-placed
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-ambulatory-ecg-removed
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-check-adverse-events
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-chemistry
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-chest-x-ray
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-concomitant-medications
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-ct-scan
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-ecg
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-habits
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-hematology
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-hemoglobin-a1c
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-inclusion-and-exclusion-criteria
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-informed-consent
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-medical-history
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-patient-number-assigned
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-patient-randomised
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-physical-examination
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-plasma-specimen-xanomeline
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-study-drug-record-medications-dispensed-medicati-bf9d38
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-subject-standing
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-subject-supine
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-tts-acceptability-survey
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-uninalysis
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-vital-signs-and-temperature
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-vital-signs-while-standing
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"
* entry[+].resource = usdm-act-vital-signs-while-supine
* entry[=].request.method = #POST
* entry[=].request.url = "ActivityDefinition"

// ── Questionnaires (instrument activities) ────────────────────────────────────
* entry[+].resource = usdm-q-adas-cog
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-apo-e-genotype
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-cibic-plus
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-dad
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-date-of-birth
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-haschinski-ischemic-scale
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-mmse
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-npi-x
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"
* entry[+].resource = usdm-q-placebo-tts-test
* entry[=].request.method = #POST
* entry[=].request.url = "Questionnaire"

// ── Observation Definitions — vital-signs panels ──────────────────────────────
* entry[+].resource = usdm-obs-vscat1-panel-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-vscat2-panel-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-vital-signs-and-temperature-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-vital-signs-while-supine-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-vital-signs-while-standing-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Observation Definitions — hematology panel ────────────────────────────────
* entry[+].resource = usdm-obs-hematology-lab-panel
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-hemoglobin
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-hematocrit
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-rbc
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-mcv
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-mch
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-mchc
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-wbc
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-neutrophils-seg
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-neutrophils-bands
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-lymphocytes
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-monocytes
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-eosinophils
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-basophils
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-platelet
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-cell-morphology
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Observation Definitions — chemistry panel ─────────────────────────────────
* entry[+].resource = usdm-obs-chemistry-lab-panel
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-sodium
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-potassium
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-bicarbonate
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-chloride
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-total-bilirubin
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-alp
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-ggt
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-alt-sgpt
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-ast-sgot
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-bun
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-creatinine
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-uric-acid
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-phosphorus
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-calcium
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-glucose-nonfasting
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-total-protein
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-albumin
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-cholesterol
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-ck
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Observation Definitions — urinalysis panel ────────────────────────────────
* entry[+].resource = usdm-obs-uninalysis-lab-panel
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-color
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-specific-gravity
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-ph
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-protein
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-glucose
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-ketones
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-bilirubin
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-urobilinogen
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-blood
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-nitrite
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-sediment-microscopy
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Observation Definitions — thyroid panel ───────────────────────────────────
* entry[+].resource = usdm-obs-thyroid-lab-panel
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-free-thyroid-index
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-t3-uptake
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-t4
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-tsh
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Observation Definitions — other tests ─────────────────────────────────────
* entry[+].resource = usdm-obs-other-lab-panel
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-folate
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-vitamin-b12
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-syphilis-screening
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-hba1c
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Observation Definitions — other analytes ──────────────────────────────────
* entry[+].resource = usdm-obs-informed-consent-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-physical-examination-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-medical-history-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-habits-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-ecg-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-concomitant-medications-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-hemoglobin-a1c-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"
* entry[+].resource = usdm-obs-adverse-events-obs
* entry[=].request.method = #POST
* entry[=].request.url = "ObservationDefinition"

// ── Protocol design (master SoA PlanDefinition) ───────────────────────────────
* entry[+].resource = H2Q-MC-LZZT-ProtocolDesign-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-ProtocolDesign-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"

// ── Visit PlanDefinitions (with soaTimepoint timing + soaTransition edges) ────
* entry[+].resource = H2Q-MC-LZZT-E1-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E1-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E2-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E2-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E3-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E3-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E4-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E4-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E5-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E5-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E7-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E7-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E8-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E8-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E9-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E9-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E10-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E10-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E11-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E11-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E12-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E12-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
* entry[+].resource = H2Q-MC-LZZT-E13-USDM
* entry[=].fullUrl = "PlanDefinition/H2Q-MC-LZZT-E13-USDM"
* entry[=].request.method = #POST
* entry[=].request.url = "PlanDefinition"
