#!/usr/bin/env python3
"""Generate Schedule-of-Activities FSH from CSV definitions.

stdlib only. Emits idempotent, DO-NOT-EDIT FSH for measurement activities
(archetype 1). See docs/superpowers/specs for the design.
"""
import csv
import pathlib

HEADER = (
    "// DO NOT EDIT — generated by scripts/gen-activities.py\n"
    "// Source: {source}\n\n"
)


def render_measurement(row):
    """FSH for one measurement ActivityDefinition + its result link."""
    return (
        f"Instance: {row['id']}\n"
        f"InstanceOf: StudyActivitySoa\n"
        f"Usage: #example\n"
        f'Title: "{row["title"]}"\n'
        f'Description: "{row["description"]}"\n'
        f"* insert VitalSignActivity({row['oidsys']}, {row['oid']}, "
        f"{row['loinc']}, [[{row['loinc_display']}]])\n"
        f"* observationResultRequirement = "
        f'"ObservationDefinition/{row["obsdef_id"]}"\n'
    )


def render_measurement_obs(row):
    """FSH for the ObservationDefinition a measurement must produce."""
    return (
        f"Instance: {row['obsdef_id']}\n"
        f"InstanceOf: ObservationDefinition\n"
        f"Usage: #example\n"
        f'Title: "{row["title"]} - Observation"\n'
        f'Description: "Result requirement for {row["title"]}"\n'
        f"* insert VitalSignObservation({row['loinc']}, "
        f"[[{row['loinc_display']}]], {row['unit']})\n"
    )


def generate_measurements(csv_path, out_path):
    with open(csv_path, newline="") as f:
        rows = list(csv.DictReader(f))
    parts = [HEADER.format(source=pathlib.Path(csv_path).name)]
    for row in rows:
        parts.append(render_measurement(row))
        parts.append("\n")
        parts.append(render_measurement_obs(row))
        parts.append("\n")
    pathlib.Path(out_path).write_text("".join(parts))


def main():
    base = pathlib.Path(__file__).resolve().parent.parent
    generate_measurements(
        base / "input/data/measurement-activities.csv",
        base / "input/fsh/generated/Measurement-Activities.gen.fsh",
    )
    print("Generated measurement activities.")


if __name__ == "__main__":
    main()
