#!/usr/bin/env python3
"""Generate Schedule-of-Activities FSH from CSV definitions.

stdlib only. Emits idempotent, DO-NOT-EDIT FSH for measurement activities
(archetype 1). See docs/superpowers/specs for the design.
"""
import csv
import sys
import pathlib

HEADER = (
    "// DO NOT EDIT — generated by scripts/gen-activities.py\n"
    "// Source: {source}\n\n"
)


def render_measurement(row):
    """FSH for one measurement ActivityDefinition + its result link."""
    return (
        f"Instance: {row['id']}\n"
        f"InstanceOf: StudyActivitySoa\n"
        f"Usage: #example\n"
        f'Title: "{row["title"]}"\n'
        f'Description: "{row["description"]}"\n'
        f"* insert VitalSignActivity({row['oidsys']}, {row['oid']}, "
        f"{row['loinc']}, [[{row['loinc_display']}]])\n"
        f"* observationResultRequirement = "
        f'"ObservationDefinition/{row["obsdef_id"]}"\n'
    )


if __name__ == "__main__":
    sys.exit(0)
