#!/usr/bin/env python3
"""
lab_panels_to_fsh.py — Generate FHIR Shorthand (FSH) from lab-panels.csv.

Reads:
  input/data/lab-panels.csv          — hand-authored lab panel / analyte definitions
  input/data/usdm-activity-catalog.csv — to confirm which panel_ids are recognised activities

Writes:
  input/fsh/generated/usdm/LabPanels.gen.fsh

For each unique panel_id in lab-panels.csv the script emits:
  • One ObservationDefinition (panel) with hasMember links to every analyte in that panel
  • One ObservationDefinition (analyte) per row, with LOINC code, unit, permittedDataType
  • One ActivityDefinition per panel whose panel_id appears in the activity catalog

Resource id conventions (consistent with usdm_reader.py):
  ObservationDefinition panel  : usdm-obs-<panel_id>-lab-panel
  ObservationDefinition analyte: usdm-obs-<analyte_id>
  ActivityDefinition           : usdm-act-<panel_id>  (only if in activity catalog)

Usage:
  python3 scripts/lab_panels_to_fsh.py [--lab-csv PATH] [--catalog PATH] [--out PATH]
"""

import argparse
import csv
import os
import re
import sys

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_DEFAULT_LAB_CSV = os.path.join(_REPO_ROOT, "input", "data", "lab-panels.csv")
_DEFAULT_CATALOG = os.path.join(_REPO_ROOT, "input", "data", "usdm-activity-catalog.csv")
_DEFAULT_OUT = os.path.join(
    _REPO_ROOT, "input", "fsh", "generated", "usdm", "LabPanels.gen.fsh"
)

_HEADER_COMMENT = "// DO NOT EDIT — generated by scripts/lab_panels_to_fsh.py"

# datatype → FHIR permittedDataType code
_DATATYPE_MAP = {
    "quantity": "Quantity",
    "string": "string",
    "integer": "integer",
    "ordinal": "CodeableConcept",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_csv_skip_comments(path: str) -> list:
    """Read a CSV file, skipping lines whose first non-whitespace char is '#'."""
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(
            (line for line in f if not line.lstrip().startswith("#"))
        )
        for row in reader:
            rows.append({k: (v or "").strip() for k, v in row.items()})
    return rows


def _slugify(text: str) -> str:
    """Lowercase, underscores/spaces/slashes/commas → hyphens, strip specials."""
    t = text.lower()
    t = re.sub(r"[\s_/,()+]+", "-", t)
    t = re.sub(r"[^a-z0-9-]", "", t)
    t = re.sub(r"-+", "-", t).strip("-")
    return t


def _fsh_id(raw: str) -> str:
    """Ensure the id is a valid FHIR id (≤64 chars, [A-Za-z0-9\\-.])."""
    slug = _slugify(raw)
    if len(slug) > 64:
        # Truncate and append a short hash suffix
        import hashlib
        suffix = hashlib.md5(slug.encode()).hexdigest()[:6]
        slug = slug[:57] + "-" + suffix
    return slug


# ---------------------------------------------------------------------------
# Core emitter
# ---------------------------------------------------------------------------

def generate(lab_csv: str, catalog_csv: str, out_path: str) -> None:
    lab_rows = _load_csv_skip_comments(lab_csv)
    if not lab_rows:
        print("ERROR: lab-panels.csv is empty or has no data rows.", file=sys.stderr)
        sys.exit(1)

    catalog_rows = _load_csv_skip_comments(catalog_csv)
    catalog_ids = {r["id"] for r in catalog_rows if r.get("id")}

    # --- Index lab rows by panel_id ---
    # panels: ordered dict panel_id → {title, loinc, analytes: [row, ...]}
    panels: dict = {}
    for row in lab_rows:
        pid = row.get("panel_id", "").strip()
        if not pid:
            continue
        if pid not in panels:
            panels[pid] = {
                "title": row.get("panel_title", pid),
                "loinc": row.get("panel_loinc", "").strip(),
                "analytes": [],
            }
        panels[pid]["analytes"].append(row)

    lines = [_HEADER_COMMENT, ""]

    # --- Emit one block per panel ---
    for panel_id, panel in panels.items():
        panel_obs_id = _fsh_id(f"usdm-obs-{panel_id}-lab-panel")
        panel_title = panel["title"]
        panel_loinc = panel["loinc"]
        analytes = panel["analytes"]
        act_id = _fsh_id(f"usdm-act-{panel_id}")

        # ---- Panel ObservationDefinition ----
        lines += [
            f"// ObservationDefinition panel: {panel_id}",
            f"Instance: {panel_obs_id}",
            "InstanceOf: ObservationDefinition",
            "Usage: #definition",
            f'Title: "{panel_title}"',
            f'Description: "Lab-derived panel observation definition for {panel_id}"',
            "* status = #active",
            "* code",
        ]
        if panel_loinc:
            lines += [
                "  * coding[+]",
                '    * system = "http://loinc.org"',
                f"    * code = #{panel_loinc}",
                f'    * display = "{panel_title}"',
            ]
        else:
            lines += [f'  * text = "{panel_title}" // TODO: add LOINC panel code']

        # hasMember links to each analyte
        for analyte_row in analytes:
            aid_raw = analyte_row.get("analyte_id", "").strip()
            if not aid_raw:
                continue
            analyte_obs_id = _fsh_id(f"usdm-obs-{aid_raw}")
            lines.append(f"* hasMember[+] = Reference({analyte_obs_id})")

        lines.append("")

        # ---- Analyte ObservationDefinitions ----
        for analyte_row in analytes:
            aid_raw = analyte_row.get("analyte_id", "").strip()
            if not aid_raw:
                continue
            analyte_obs_id = _fsh_id(f"usdm-obs-{aid_raw}")
            analyte_title = analyte_row.get("analyte_title", aid_raw)
            loinc = analyte_row.get("loinc", "").strip()
            loinc_display = analyte_row.get("loinc_display", analyte_title).strip()
            unit = analyte_row.get("unit", "").strip()
            datatype_raw = analyte_row.get("datatype", "quantity").strip() or "quantity"
            fhir_datatype = _DATATYPE_MAP.get(datatype_raw, "string")

            lines += [
                f"// ObservationDefinition analyte: {aid_raw}",
                f"Instance: {analyte_obs_id}",
                "InstanceOf: ObservationDefinition",
                "Usage: #definition",
                f'Title: "{analyte_title}"',
                f'Description: "Lab-derived analyte observation definition for {aid_raw}"',
                "* status = #active",
                "* code",
            ]
            if loinc:
                lines += [
                    "  * coding[+]",
                    '    * system = "http://loinc.org"',
                    f"    * code = #{loinc}",
                    f'    * display = "{loinc_display}"',
                ]
            else:
                lines += [f'  * text = "{analyte_title}" // TODO: add LOINC code']

            lines.append(f"* permittedDataType = #{fhir_datatype}")
            if unit and fhir_datatype == "Quantity":
                lines.append(f'* permittedUnit = UCUM#{unit}')
            lines.append("")

        # ---- ActivityDefinition (only if panel_id is a known activity) ----
        if panel_id in catalog_ids:
            # Look up catalog row for code info
            cat_row = next((r for r in catalog_rows if r["id"] == panel_id), {})
            code_system = cat_row.get("code_system", "").strip()
            code = cat_row.get("code", "").strip()
            code_display = cat_row.get("code_display", panel_title).strip()

            lines += [
                f"// ActivityDefinition: {panel_id} (measurement — lab panel)",
                f"Instance: {act_id}",
                "InstanceOf: ActivityDefinition",
                "Usage: #definition",
                f'Title: "{panel_title}"',
                f'Description: "Lab-derived activity definition for {panel_id}"',
                "* status = #active",
                "* kind = #ServiceRequest",
                "* intent = #plan",
                "* code",
            ]
            if code and code_system:
                lines += [
                    "  * coding[+]",
                    f'    * system = "{code_system}"',
                    f"    * code = #{code}",
                    f'    * display = "{code_display}"',
                ]
            else:
                lines += [f'  * text = "{panel_title}" // TODO: add activity code']

            lines.append(f"* observationResultRequirement[+] = Canonical({panel_obs_id})")
            lines.append("")
        else:
            lines += [
                f"// NOTE: panel_id '{panel_id}' not found in usdm-activity-catalog.csv",
                f"// No ActivityDefinition emitted. Add it to the catalog to generate one.",
                "",
            ]

    # Write output
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    content = "\n".join(lines)
    # Ensure single trailing newline
    content = content.rstrip("\n") + "\n"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  → {out_path}")
    print(f"     {len(panels)} panels, "
          f"{sum(len(p['analytes']) for p in panels.values())} analytes written")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate LabPanels.gen.fsh from lab-panels.csv"
    )
    parser.add_argument(
        "--lab-csv", default=_DEFAULT_LAB_CSV,
        help=f"Path to lab-panels.csv (default: {_DEFAULT_LAB_CSV})"
    )
    parser.add_argument(
        "--catalog", default=_DEFAULT_CATALOG,
        help=f"Path to usdm-activity-catalog.csv (default: {_DEFAULT_CATALOG})"
    )
    parser.add_argument(
        "--out", default=_DEFAULT_OUT,
        help=f"Output FSH file path (default: {_DEFAULT_OUT})"
    )
    args = parser.parse_args()
    generate(args.lab_csv, args.catalog, args.out)


if __name__ == "__main__":
    main()
