#!/usr/bin/env python3
"""
usdm_catalogs.py — Activity & Observation catalog extraction from USDM JSON.

Standalone module for Task F-5.  Designed to be merged into usdm_reader.py
once F-1 lands.  All logic is pure-Python stdlib; no pip installs.

Public API
----------
extract_activity_catalog(usdm_path)    -> list[dict]
extract_observation_catalog(usdm_path) -> list[dict]
write_activity_catalog(rows, out_path)
write_observation_catalog(rows, out_path)
"""

import csv
import json
import logging
import pathlib
import re
import sys
import warnings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# CSV header comment required by spec
# ---------------------------------------------------------------------------
_CSV_HEADER_COMMENT = "# DO NOT EDIT — generated by scripts/usdm_to_soa.py"

# ---------------------------------------------------------------------------
# Activity catalog column order (matches spec schema)
# ---------------------------------------------------------------------------
ACTIVITY_FIELDS = [
    "id", "oid", "oidsys", "title", "archetype",
    "code_system", "code", "code_display", "unit",
    "result_obsdef_id", "questionnaire_id", "respondent_type",
    "default_condition",
]

# ---------------------------------------------------------------------------
# Observation catalog column order (matches spec schema)
# ---------------------------------------------------------------------------
OBSERVATION_FIELDS = [
    "obsdef_id", "kind", "member_of", "code", "code_display", "unit", "datatype",
]

# ---------------------------------------------------------------------------
# Instrument respondent_type lookup table (from spec §Task F-5)
# Key: BiomedicalConceptSurrogate id
# ---------------------------------------------------------------------------
_SURROGATE_RESPONDENT = {
    "BiomedicalConceptSurrogate_1": "practitioner",   # Demographics / Date of Birth
    "BiomedicalConceptSurrogate_2": "practitioner",   # Hachinski Ischemic Scale
    "BiomedicalConceptSurrogate_3": "practitioner",   # MMSE
    "BiomedicalConceptSurrogate_4": "practitioner",   # Apo E Genotype
    "BiomedicalConceptSurrogate_5": "patient",        # Placebo TTS test
}

# ---------------------------------------------------------------------------
# Slugify helper
# ---------------------------------------------------------------------------
# Characters to convert to hyphens (spaces, slashes, commas, parentheses)
_SLUG_TO_HYPHEN = re.compile(r"[\s/,()+]+")
# Characters to strip entirely (anything not alphanumeric or hyphen)
_SLUG_STRIP = re.compile(r"[^a-z0-9-]")


def _slugify(text: str) -> str:
    """Lowercase, spaces/slashes/commas/parens → hyphens, strip special chars."""
    t = text.lower()
    t = _SLUG_TO_HYPHEN.sub("-", t)   # convert separators to hyphens first
    t = _SLUG_STRIP.sub("", t)         # strip remaining non-alphanumeric chars
    t = re.sub(r"-+", "-", t).strip("-")
    return t


# ---------------------------------------------------------------------------
# USDM index builder
# ---------------------------------------------------------------------------

def _build_index(data: dict) -> dict:
    """
    Walk the entire USDM JSON tree and build a flat id→object index.
    Any object with an "id" field (non-null) is indexed.
    """
    index: dict = {}

    def _walk(node):
        if isinstance(node, dict):
            nid = node.get("id")
            if nid:
                index[nid] = node
            for v in node.values():
                _walk(v)
        elif isinstance(node, list):
            for item in node:
                _walk(item)

    _walk(data)
    return index


# ---------------------------------------------------------------------------
# Unit extraction from a BiomedicalConcept
# ---------------------------------------------------------------------------

def _extract_unit(bc: dict) -> str:
    """
    Return the unit string for a BiomedicalConcept.

    Strategy (per spec §2.8):
      1. Find the property whose name starts with "VSORRES" (result-value property).
         The *next* property (VSORRESU) carries the unit.
      2. If the VSORRESU property has responseCodes, use the first responseCode's
         code.decode as the unit string.
      3. If no responseCodes, use the VSORRESU property's code.standardCode.decode.
      4. If no VSORRESU property found, return "".

    The USDM uses CDISC decode strings (e.g. "Degree Celsius", "Kilogram").
    We return those as-is; downstream enrichment (F-5b) can map to UCUM.
    """
    props = bc.get("properties", [])
    for i, prop in enumerate(props):
        name = prop.get("name", "")
        # Match VSORRESU-style property (unit property)
        if re.match(r"VSORRESU", name, re.IGNORECASE) or re.match(r".*ORRESU.*", name):
            # Try responseCodes first
            rc = prop.get("responseCodes", [])
            if rc:
                return rc[0].get("code", {}).get("decode", "")
            # Fall back to property code decode
            code_obj = prop.get("code", {})
            sc = code_obj.get("standardCode", {})
            return sc.get("decode", "")
    return ""


def _extract_datatype(bc: dict) -> str:
    """
    Return "Quantity" for numeric BCs, "string" for non-numeric.

    Looks for the VSORRES property (result value) and checks its datatype field.
    Numeric datatypes: float, integer, decimal, number.
    """
    props = bc.get("properties", [])
    for prop in props:
        name = prop.get("name", "")
        if re.match(r"VSORRES", name, re.IGNORECASE) or re.match(r".*ORRES(?!U).*", name):
            dt = prop.get("datatype", "").lower()
            if dt in ("float", "integer", "decimal", "number", "int"):
                return "Quantity"
            if dt:
                return "string"
    return "string"


# ---------------------------------------------------------------------------
# Core extraction functions
# ---------------------------------------------------------------------------

def _load_usdm(usdm_path: str) -> tuple:
    """Load USDM JSON and return (data, index, study_version, study_design).

    USDM v4 nesting:
      study.versions[0]                    → study_version
        .studyDesigns[0]                   → study_design  (activities, encounters, etc.)
        .biomedicalConcepts[]              → BCs (at versions[0] level, NOT studyDesigns[0])
        .bcCategories[]                    → BCCategories (at versions[0] level)
        .bcSurrogates[]                    → BCSurrogates (at versions[0] level)
    """
    with open(usdm_path, encoding="utf-8") as f:
        data = json.load(f)
    index = _build_index(data)
    study_version = data["study"]["versions"][0]
    study_design = study_version["studyDesigns"][0]
    return data, index, study_version, study_design


def extract_activity_catalog(usdm_path: str) -> list:
    """
    Extract the activity catalog from a USDM JSON file.

    Returns a list of dicts with keys matching ACTIVITY_FIELDS.

    Classification decision tree (per spec §Task F-5 + audit Appendix B):
      1. bcSurrogateIds non-empty        → archetype = instrument
         (surrogate wins even when biomedicalConceptIds also present — e.g.
          Activity_4 Demographics has both BC_20/21 and BCSurr_1; the clinical
          purpose is the Date of Birth questionnaire, so instrument takes precedence.
          This ensures all 5 BCSurrogates map to instrument rows as required.)
      2. biomedicalConceptIds non-empty  → archetype = measurement
         (BC wins over definedProcedures — e.g. Activity_7 Physical examination
          has both BC_34 and Procedure_5; BC takes precedence per spec.)
      3. bcCategoryIds non-empty         → archetype = measurement (panel via category)
      4. definedProcedures[0] with code  → archetype = procedure
      5. else                            → WARNING "unclassified:<id>", skip

    Skipped (header/grouping) activities — justified below:
      Activity_0  : label="" — empty label, no BC/procedure refs; pure structural
                    header row (childIds present, no clinical content)
      Activity_4a : label="All Demographics Header" — structural grouping row
                    (childIds=["Activity_4","Activity_4b","Activity_7"]; no BC/proc)
      Activity_4b : label="Scores" — structural grouping row
                    (childIds=["Activity_5","Activity_6"]; no BC/proc)
      Activity_32b: label="Vital Signs Supine/Standing" — structural grouping row
                    (no BC/proc/surrogate; timelineId only; childIds=[])
    These 4 activities have no biomedicalConceptIds, no bcSurrogateIds, no
    bcCategoryIds, and no definedProcedures with a code — they fall through all
    branches of the decision tree and would emit WARNING "unclassified:<id>".
    Per the spec ("4 are header/grouping rows — skip those"), they are intentionally
    excluded from the catalog.  The remaining 36 activities are all classified.
    """
    data, index, study_version, study_design = _load_usdm(usdm_path)

    # Build BC id → BC object map for fast lookup
    # BCs are at versions[0].biomedicalConcepts (NOT studyDesigns[0])
    bc_map = {bc["id"]: bc for bc in study_version.get("biomedicalConcepts", [])}
    # Build BCCategory id → BCCategory object map (at versions[0] level)
    bcc_map = {c["id"]: c for c in study_version.get("bcCategories", [])}
    # Build BCSurrogate id → BCSurrogate object map (at versions[0] level)
    bcs_map = {s["id"]: s for s in study_version.get("bcSurrogates", [])}

    rows = []
    seen_ids: set = set()

    for act in study_design.get("activities", []):
        act_id = act["id"]
        label = act.get("label", "").strip()
        bc_ids = act.get("biomedicalConceptIds", []) or []
        bcc_ids = act.get("bcCategoryIds", []) or []
        bcs_ids = act.get("bcSurrogateIds", []) or []
        procs = act.get("definedProcedures", []) or []

        # --- Classify ---
        # Decision tree (per spec §Task F-5):
        #   1. bcSurrogateIds non-empty  → instrument
        #      (surrogate wins over BC when both present — e.g. Activity_4 Demographics
        #       has both BC_20/21 and BCSurr_1; the clinical purpose is the Date of Birth
        #       questionnaire, so instrument takes precedence)
        #   2. biomedicalConceptIds non-empty → measurement
        #      (BC wins over definedProcedures — e.g. Activity_7 Physical examination)
        #   3. bcCategoryIds non-empty   → measurement (panel via category)
        #   4. definedProcedures[0] with non-null code → procedure
        #   5. else → WARNING "unclassified:<id>", skip
        archetype = None
        code_system = ""
        code = ""
        code_display = ""
        unit = ""
        result_obsdef_id = ""
        questionnaire_id = ""
        respondent_type = ""

        if bcs_ids:
            # instrument — surrogate wins even when BC refs also present
            archetype = "instrument"
            surrogate_id = bcs_ids[0]
            surrogate = bcs_map.get(surrogate_id, {})
            # No code on surrogate (per spec §2.9)
            questionnaire_id = _slugify(surrogate.get("label", surrogate_id))
            respondent_type = _SURROGATE_RESPONDENT.get(surrogate_id, "")
            if not respondent_type:
                warnings.warn(
                    f"WARNING: instrument activity {act_id!r} surrogate "
                    f"{surrogate_id!r} has no respondent_type in lookup table"
                )

        elif bc_ids:
            # measurement — BC wins over procedure (spec precedence rule)
            archetype = "measurement"
            # Use first BC for code/unit
            bc = bc_map.get(bc_ids[0])
            if bc:
                bc_code_obj = bc.get("code", {})
                sc = bc_code_obj.get("standardCode", {})
                code_system = sc.get("codeSystem", "")
                code = sc.get("code", "")
                code_display = sc.get("decode", "")
                unit = _extract_unit(bc)

        elif bcc_ids:
            # measurement via category (panel)
            archetype = "measurement"
            # No single BC code — code comes from the category (no code field on BCCat)
            # Leave code/unit blank; downstream enrichment (F-5b) supplies LOINC panel code

        elif procs:
            # procedure — use first procedure with a non-null code
            proc = procs[0]
            proc_code = proc.get("code")
            if proc_code:
                archetype = "procedure"
                code_system = proc_code.get("codeSystem", "")
                code = proc_code.get("code", "")
                code_display = proc_code.get("decode", "")
            else:
                logger.warning("WARNING unclassified:%s (procedure with null code)", act_id)
                continue

        else:
            # Unclassified — emit warning and skip
            logger.warning("WARNING unclassified:%s", act_id)
            continue

        # Build slug id from label; fall back to act_id if label is empty
        slug = _slugify(label) if label else act_id.lower()

        # Ensure uniqueness — append act_id suffix if collision
        base_slug = slug
        suffix = 1
        while slug in seen_ids:
            slug = f"{base_slug}-{suffix}"
            suffix += 1
        seen_ids.add(slug)

        if archetype == "measurement":
            result_obsdef_id = f"{slug}-obs"

        rows.append({
            "id": slug,
            "oid": "",
            "oidsys": "",
            "title": label,
            "archetype": archetype,
            "code_system": code_system,
            "code": code,
            "code_display": code_display,
            "unit": unit,
            "result_obsdef_id": result_obsdef_id,
            "questionnaire_id": questionnaire_id,
            "respondent_type": respondent_type,
            "default_condition": "",
        })

    return rows


def extract_observation_catalog(usdm_path: str) -> list:
    """
    Extract the observation catalog from a USDM JSON file.

    Returns a list of dicts with keys matching OBSERVATION_FIELDS.

    The observation catalog is activity-driven (mirrors the existing
    observation-catalog.csv pattern):

    Panel rows:
      - One row per BiomedicalConceptCategory → kind = panel
      - obsdef_id = slugify(category.name) + "-panel-obs"
      - Activities that reference a BCCategory get result_obsdef_id pointing
        to the corresponding panel row.

    Analyte rows:
      - One row per measurement activity that references biomedicalConceptIds
        → kind = analyte, obsdef_id = <activity-slug>-obs
      - code/code_display/unit from the first BC referenced by the activity
      - datatype: Quantity for numeric BCs, string for non-numeric
      - member_of: panel obsdef_id if the activity references a BCCategory
        (via the activity's bcCategoryIds); blank otherwise

    This ensures result_obsdef_id in the activity catalog always resolves
    to a valid obsdef_id in the observation catalog.
    """
    data, index, study_version, study_design = _load_usdm(usdm_path)

    # BCs, BCCategories, BCSurrogates are at versions[0] level (NOT studyDesigns[0])
    bc_list = study_version.get("biomedicalConcepts", [])
    bcc_list = study_version.get("bcCategories", [])

    # Build BC id → BC object map
    bc_map = {bc["id"]: bc for bc in bc_list}

    # Build panel obsdef_id for each BCCategory
    # Use BCCategory.name (machine name, unique) for the slug to avoid collisions
    # when multiple categories share the same label (e.g. BCCat_3 and BCCat_4 both
    # have label="Biochemistry Category" but names "Chem_Cat1" and "Urin_Cat1").
    panel_id_map: dict = {}  # BCCat id → obsdef_id
    seen_panel_ids: set = set()
    for cat in bcc_list:
        cat_id = cat["id"]
        # Prefer name (unique machine name) over label for slug
        cat_name = cat.get("name") or cat.get("label", cat_id)
        panel_obsdef_id = _slugify(cat_name) + "-panel-obs"
        # Ensure uniqueness (defensive — names should already be unique)
        base = panel_obsdef_id
        suffix = 1
        while panel_obsdef_id in seen_panel_ids:
            panel_obsdef_id = f"{base}-{suffix}"
            suffix += 1
        seen_panel_ids.add(panel_obsdef_id)
        panel_id_map[cat_id] = panel_obsdef_id

    rows = []
    seen_obsdef_ids: set = set(seen_panel_ids)  # start with panel ids already reserved

    # --- Panel rows first ---
    for cat in bcc_list:
        panel_obsdef_id = panel_id_map[cat["id"]]
        rows.append({
            "obsdef_id": panel_obsdef_id,
            "kind": "panel",
            "member_of": "",
            "code": "",          # No code on BCCategory; F-5b enrichment supplies LOINC
            "code_display": cat.get("label", ""),
            "unit": "",
            "datatype": "",
        })

    # --- Analyte rows — one per measurement activity ---
    # We re-run the activity classification logic to get the activity slug and
    # determine which BC/BCCategory each measurement activity references.
    bcs_map = {s["id"]: s for s in study_version.get("bcSurrogates", [])}
    bcc_map = {c["id"]: c for c in bcc_list}
    seen_act_ids: set = set()

    for act in study_design.get("activities", []):
        act_id = act["id"]
        label = act.get("label", "").strip()
        bc_ids = act.get("biomedicalConceptIds", []) or []
        bcc_ids = act.get("bcCategoryIds", []) or []
        bcs_ids = act.get("bcSurrogateIds", []) or []
        procs = act.get("definedProcedures", []) or []

        # Determine archetype (same logic as extract_activity_catalog)
        if bcs_ids:
            continue  # instrument — no observation row
        elif bc_ids:
            archetype = "measurement"
        elif bcc_ids:
            archetype = "measurement"
        elif procs and procs[0].get("code"):
            continue  # procedure — no observation row
        else:
            continue  # unclassified — skip

        # Build activity slug (same logic as extract_activity_catalog)
        slug = _slugify(label) if label else act_id.lower()
        base_slug = slug
        suffix = 1
        while slug in seen_act_ids:
            slug = f"{base_slug}-{suffix}"
            suffix += 1
        seen_act_ids.add(slug)

        obsdef_id = f"{slug}-obs"

        # Ensure obsdef_id uniqueness (defensive)
        base = obsdef_id
        suffix = 1
        while obsdef_id in seen_obsdef_ids:
            obsdef_id = f"{base}-{suffix}"
            suffix += 1
        seen_obsdef_ids.add(obsdef_id)

        # Get code/unit/datatype from first BC
        code = ""
        code_display = ""
        unit = ""
        datatype = ""
        member_of = ""

        if bc_ids:
            bc = bc_map.get(bc_ids[0])
            if bc:
                bc_code_obj = bc.get("code", {})
                sc = bc_code_obj.get("standardCode", {})
                code = sc.get("code", "")
                code_display = sc.get("decode", "")
                unit = _extract_unit(bc)
                datatype = _extract_datatype(bc)

        elif bcc_ids:
            # Panel activity — point member_of to the BCCategory panel row
            # The activity itself gets an analyte row that is a member of the panel
            member_of = panel_id_map.get(bcc_ids[0], "")
            # No code/unit from BCCategory directly; F-5b enrichment supplies these

        rows.append({
            "obsdef_id": obsdef_id,
            "kind": "analyte",
            "member_of": member_of,
            "code": code,
            "code_display": code_display,
            "unit": unit,
            "datatype": datatype,
        })

    return rows


# ---------------------------------------------------------------------------
# CSV writers
# ---------------------------------------------------------------------------

def write_activity_catalog(rows: list, out_path) -> None:
    """Write activity catalog rows to a CSV file with the DO NOT EDIT header."""
    out_path = pathlib.Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        f.write(_CSV_HEADER_COMMENT + "\n")
        writer = csv.DictWriter(f, fieldnames=ACTIVITY_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def write_observation_catalog(rows: list, out_path) -> None:
    """Write observation catalog rows to a CSV file with the DO NOT EDIT header."""
    out_path = pathlib.Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        f.write(_CSV_HEADER_COMMENT + "\n")
        writer = csv.DictWriter(f, fieldnames=OBSERVATION_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# CLI entry point (for standalone use / testing)
# ---------------------------------------------------------------------------

def main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(
        description="Extract activity and observation catalogs from a USDM JSON file."
    )
    parser.add_argument("usdm_path", help="Path to USDM JSON file")
    parser.add_argument(
        "--activity-out",
        default="input/data/usdm-activity-catalog.csv",
        help="Output path for activity catalog CSV",
    )
    parser.add_argument(
        "--observation-out",
        default="input/data/usdm-observation-catalog.csv",
        help="Output path for observation catalog CSV",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    act_rows = extract_activity_catalog(args.usdm_path)
    obs_rows = extract_observation_catalog(args.usdm_path)

    write_activity_catalog(act_rows, args.activity_out)
    write_observation_catalog(obs_rows, args.observation_out)

    print(f"Activity catalog:    {len(act_rows)} rows → {args.activity_out}")
    print(f"Observation catalog: {len(obs_rows)} rows → {args.observation_out}")

    # Summary by archetype
    from collections import Counter
    arch_counts = Counter(r["archetype"] for r in act_rows)
    for arch, cnt in sorted(arch_counts.items()):
        print(f"  {arch}: {cnt}")


if __name__ == "__main__":
    main()
